### ISSUE TITLE
avoid clobbering scala package namespace

### ISSUE THREAD

**Issue by graingert** [alonsodomin/cron4s#57]
Could you move your package namespace to com.github.alonsodomin.cron4s ?

**Comment by alonsodomin** [comment]
Hi @graingert, can you describe what kind of problem do you have right now?

The lib uses `cron4s` as package name, moving it to `com.github.alonsodomin.cron4s` makes it really awkward to use it in a REPL session.

Can you describe what kind of benefit the package rename will give you?

**Comment by alonsodomin** [comment]
closing this due to unclear.
