### ISSUE TITLE
support every 5 mins notation ('0 0/5 * ? * *')

### ISSUE THREAD

**Issue by pjfanning** [alonsodomin/cron4s#98]
Would it be feasible to support expressions like '0 0/5 * ? * *'?
I can workaround this in cron4s with '0 0,5,10,15,20,25,30,35,40,45,50,55 * ? * *' but it's not a nice workaround.

**Comment by alonsodomin** [comment]
Hi @pjfanning, yeah, it should be possible to support those, what is the issue that you are facing? There must be a problem in the expression evaluator if you can't...

**Comment by pjfanning** [comment]
With the following code with cron4s 0.4.5, I'm getting `Expected '0-59' at position 2 but found '"0/5 * ? * *"'`:

```
import cron4s.Cron
import cron4s.lib.javatime._

  checkCron("0 0/5 * ? * *")

  private def checkCron(cron: String): Unit = {
    Cron(cron) match {
      case Right(parsedExp) => parsedExp.next(LocalDateTime.now) mustBe defined
      case Left(err) => throw err
    }
  }
```

**Comment by alonsodomin** [comment]
That is a bug in the parser. I'll take a look at it.

**Comment by alonsodomin** [comment]
@pjfanning I've been considering this but, in reality, there is no bug in the parser itself. When using the expression `x/y`, the `x` part must be divisible by the `y` part, this can be a sequence of numbers separated by commas, a range or a special character.

When using a constant value in the `x` part (like `0`), the parser is not considering that one a divisible value and fails. The error message is not really good in that case and I'll look at ways of improving it.

So, the actual expression that you are after is `0 */5 * ? * *` which basically means _every five minutes_. Not sure if all other cron parsers accept the `0/5` as a valid expression though.

**Comment by pjfanning** [comment]
thanks @alonsodomin - I can work with the */5 notation
